name: scale

services:

  proxy:
    image: nginx:1.27-alpine
    container_name: scale-proxy
    volumes:
      - ./scale.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "80:80"
    restart: unless-stopped

  app:
    image: traefik/whoami:v1.10
    restart: unless-stopped

  slow:
    image: mccutchen/go-httpbin:v2.15.0
    restart: unless-stopped
