name: scalare

services:

  proxy:
    image: nginx:1.27-alpine
    container_name: scalare-proxy
    volumes:
      - ./conf:/etc/nginx/conf.d:ro
    ports:
      - "80:80"
    restart: unless-stopped

  web:
    image: nginx:1.27-alpine
    container_name: scalare-web
    volumes:
      - ./web:/usr/share/nginx/html:ro
    restart: unless-stopped

  api-1:
    image: traefik/whoami:v1.10
    container_name: scalare-api-1
    command: ["--name=api-1"]
    restart: unless-stopped

  api-2:
    image: traefik/whoami:v1.10
    container_name: scalare-api-2
    command: ["--name=api-2"]
    restart: unless-stopped

  api-3:
    image: traefik/whoami:v1.10
    container_name: scalare-api-3
    command: ["--name=api-3"]
    restart: unless-stopped
