server {
    listen 80;
    server_name _;

    location /whoami/ { proxy_pass http://127.0.0.1:8101/; }
    location /hello/ { proxy_pass http://127.0.0.1:8102/; }
    location /httpbin/get { proxy_pass http://127.0.0.1:8103/get; }
    location /adminer/ { proxy_pass http://127.0.0.1:8104/; }
    location /mail/ { proxy_pass http://127.0.0.1:8105/; }
    location /logs/ { proxy_pass http://127.0.0.1:8106/; }
    location /files/ { proxy_pass http://127.0.0.1:8107/; }
    location /docs/ { proxy_pass http://127.0.0.1:8108/; }
    location /prom/graph { proxy_pass http://127.0.0.1:8109/graph; }
    location /node/metrics { proxy_pass http://127.0.0.1:8110/metrics; }
    location /grafana/login { proxy_pass http://127.0.0.1:8111/login; }
    location /chef/ { proxy_pass http://127.0.0.1:8112/; }
}

