server {
    listen 80;
    server_name cloud.54.85.50.57.nip.io;

    proxy_http_version 1.1;
    proxy_set_header Host              $host;
    proxy_set_header X-Real-IP         $remote_addr;
    proxy_set_header X-Forwarded-For   $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;

    location = /whoami       { return 301 /whoami/; }
    location = /hello        { return 301 /hello/; }
    location = /httpbin      { return 301 /httpbin/; }
    location = /adminer      { return 301 /adminer/; }
    location = /mailpit      { return 301 /mailpit/; }
    location = /dozzle       { return 301 /dozzle/; }
    location = /filebrowser  { return 301 /filebrowser/; }
    location = /swagger-ui   { return 301 /swagger-ui/; }
    location = /prometheus   { return 301 /prometheus/; }
    location = /node-exporter { return 301 /node-exporter/; }
    location = /grafana      { return 301 /grafana/; }
    location = /cyberchef    { return 301 /cyberchef/; }
    location = /uptime-kuma  { return 301 /uptime-kuma/; }
    location = /it-tools     { return 301 /it-tools/; }

  
    location /whoami/ {
        proxy_pass http://127.0.0.1:8101/;
    }

    location /hello/ {
        proxy_pass http://127.0.0.1:8102/;
    }

    location /httpbin/ {
        proxy_pass http://127.0.0.1:8103/;
    }

    location /adminer/ {
        proxy_pass http://127.0.0.1:8104/;
    }

    location /mailpit/ {
        proxy_pass http://127.0.0.1:8105/;
    }

    location /dozzle/ {
        proxy_pass http://127.0.0.1:8106/;
    }

    location /filebrowser/ {
        proxy_pass http://127.0.0.1:8107/;
    }

    location /swagger-ui/ {
        proxy_pass http://127.0.0.1:8108/;
    }

    location /prometheus/ {
        proxy_pass http://127.0.0.1:8109/;
    }

    location /node-exporter/ {
        proxy_pass http://127.0.0.1:8110/;
    }

    location /grafana/ {
        proxy_pass http://127.0.0.1:8111/;
    }

    location /cyberchef/ {
        proxy_pass http://127.0.0.1:8112/;
    }

    location /uptime-kuma/ {
        proxy_pass http://127.0.0.1:8113/;
    }

    location /it-tools/ {
        proxy_pass http://127.0.0.1:8114/;
    }

    location = / {
        default_type text/plain;
        return 200 "Cloud Demo Apps:\n- /whoami/\n- /hello/\n- /httpbin/\n- /adminer/\n- /mailpit/\n- /dozzle/\n- /filebrowser/\n- /swagger-ui/\n- /prometheus/\n- /node-exporter/\n- /grafana/\n- /cyberchef/\n- /uptime-kuma/\n- /it-tools/\n";
    }
}
