version: '3.8'

services:

  mysql:
    image: mysql:8.4
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"
    volumes:
      - mysql_all_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 20s

    restart: unless-stopped


  online-shop:
    image: sebi123q/sebi-online-shop:0.0.2
    container_name: sebi-online-shop
    ports:
      - "8087:8081"
    environment:
      DB_URL: jdbc:mysql://mysql:3306/online_shop_spring?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&createDatabaseIfNotExist=true}
      JPA_SHOW_SQL: "true"
    depends_on:
      mysql:
        condition: service_healthy
    restart: unless-stopped

volumes:
  mysql_all_data:





