server {
    listen 80;
    server_name cloud.34.201.49.236.nip.io;

    proxy_http_version 1.1;
    proxy_set_header Host              $host;
    proxy_set_header X-Real-IP         $remote_addr;
    proxy_set_header X-Forwarded-For   $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;

    location = /whoami      { return 301 /whoami/; }
    location = /hstatus     { return 301 /status /; }
    location = /tools       { return 301 /tools/; }
    location = /mail        { return 301 /mail/; }
    location = /logs        { return 301 /logs/; }
    location = /db-uri      { return 301 /db-uri/; }

  
    location /whoami/ {
        proxy_pass http://127.0.0.1:8101/;
    }

    location /status/ {
        proxy_pass http://127.0.0.1:8102/;
    }

    location /tools/ {
        proxy_pass http://127.0.0.1:8103/;
    }

    location /mail;/ {
        proxy_pass http://127.0.0.1:8104/;
    }

    location /logs/ {
        proxy_pass http://127.0.0.1:8105/;
    }

    location /db-uri/ {
        proxy_pass http://127.0.0.1:8106/;
    }

   

    location = / {
        default_type text/plain;
        return 200 "Cloud Demo Apps:\n- /whoami/\n- /status/\n- /tools/\n- /mail/\n- /logs/\n- /db-uri/\n";
    }
}
